In [13]:
import json 

In [14]:
# add json file 
with open ('bank.json') as f:
    data = json.load (f)
data

{'customer_information': {'1234': {'name': 'sk', 'balance': 100000},
  '1235': {'name': 'pushpita', 'balance': 25000},
  '1231': {'name': 'meghashree', 'balance': 1000},
  '1236': {'name': 'sanchari', 'balance': 25600},
  '1237': {'name': 'uma', 'balance': 3000},
  '1238': {'name': 'subhadip', 'balance': 2500},
  '1239': {'name': 'rahul', 'balance': 1000},
  '1068': {'name': 'roy', 'balance': 5000}},
 'Transaction': {'TR101': {'from': 1234, 'to': 9810, 'amt': 5000},
  'TR102': {'from': 9810, 'to': 1234, 'amt': 100000},
  'TR103': {'from': 1068, 'to': 9810, 'amt': 256000},
  'TR104': {'from': 9810, 'to': 1234, 'amt': 523000},
  'TR105': {'from': 1234, 'to': 1068, 'amt': 5000},
  'TR106': {'from': 9810, 'to': 1234, 'amt': 52000},
  'TR107': {'from': 1234, 'to': 9810, 'amt': 36500},
  'TR108': {'from': 1068, 'to': 1234, 'amt': 52000},
  'TR110': {'from': 1234, 'to': 9810, 'amt': 560000},
  'TR111': {'from': 9810, 'to': 1234, 'amt': 15200},
  'TR1112': {'from': 1234, 'to': 1231, 'amt': 125

In [15]:
#access the customer part
customer = data['customer_information']
# access 'Transaction' part
trans = data['Transaction']
customer
trans

{'TR101': {'from': 1234, 'to': 9810, 'amt': 5000},
 'TR102': {'from': 9810, 'to': 1234, 'amt': 100000},
 'TR103': {'from': 1068, 'to': 9810, 'amt': 256000},
 'TR104': {'from': 9810, 'to': 1234, 'amt': 523000},
 'TR105': {'from': 1234, 'to': 1068, 'amt': 5000},
 'TR106': {'from': 9810, 'to': 1234, 'amt': 52000},
 'TR107': {'from': 1234, 'to': 9810, 'amt': 36500},
 'TR108': {'from': 1068, 'to': 1234, 'amt': 52000},
 'TR110': {'from': 1234, 'to': 9810, 'amt': 560000},
 'TR111': {'from': 9810, 'to': 1234, 'amt': 15200},
 'TR1112': {'from': 1234, 'to': 1231, 'amt': 1250},
 'TR113': {'from': 9810, 'to': 1234, 'amt': 36520}}

1.print all the customers name.

In [16]:
for i in customer.keys() :
    print(customer[i]['name'].upper())
    

SK
PUSHPITA
MEGHASHREE
SANCHARI
UMA
SUBHADIP
RAHUL
ROY


2.print customer name whoes acc bal is more than 25000

In [17]:
for i in customer.keys() :
    bal=customer[i]['balance']
    if bal > 25000:
        print(bal)

100000
25600


3.print all the trans id whoes trans amount less than 10000

In [18]:
for i in trans.keys() :
    bal=trans[i]['amt']
    if bal > 10000:
        print('id', i,'rs', trans[i]['amt'])

id TR102 rs 100000
id TR103 rs 256000
id TR104 rs 523000
id TR106 rs 52000
id TR107 rs 36500
id TR108 rs 52000
id TR110 rs 560000
id TR111 rs 15200
id TR113 rs 36520


4.print all the trans id whoes trans amount is odd or even

In [19]:
for i in trans.keys() :
    bal=trans[i]['amt']
    if bal % 2 ==0:
        print('id', i, 'even')
    else:
        print('id', i, 'odd')

id TR101 even
id TR102 even
id TR103 even
id TR104 even
id TR105 even
id TR106 even
id TR107 even
id TR108 even
id TR110 even
id TR111 even
id TR1112 even
id TR113 even


5.print all the trans id for acc no 1068


In [20]:
for i in trans.keys() :
    acc = trans[i]['from']
    if acc == 1068:
        print(i)

TR103
TR108


6.print all the trans for sk's acc


In [21]:
for i in customer.keys():
    if customer[i]['name'] == 'sk':
        acc1 = i
for i in trans.keys() :
    acc = trans[i]['from']
    if acc == int(acc1) :
        print(trans[i])
   


{'from': 1234, 'to': 9810, 'amt': 5000}
{'from': 1234, 'to': 1068, 'amt': 5000}
{'from': 1234, 'to': 9810, 'amt': 36500}
{'from': 1234, 'to': 9810, 'amt': 560000}
{'from': 1234, 'to': 1231, 'amt': 1250}


7.update account balance of acc 1235 to 5000 and deduciton of 1068

In [24]:
for i in customer.keys():
    if i == '1068':
        customer[i]['balance'] -= 5000
        print(customer[i])
    elif i == '1235':
        customer[i]['balance'] += 5000
        print(customer[i])
trans['TT114']= {'from': 1068, 'to': 1235, 'amt': 5000}

{'name': 'pushpita', 'balance': 25000}
{'name': 'roy', 'balance': 5000}


In [25]:
data

{'customer_information': {'1234': {'name': 'sk', 'balance': 100000},
  '1235': {'name': 'pushpita', 'balance': 25000},
  '1231': {'name': 'meghashree', 'balance': 1000},
  '1236': {'name': 'sanchari', 'balance': 25600},
  '1237': {'name': 'uma', 'balance': 3000},
  '1238': {'name': 'subhadip', 'balance': 2500},
  '1239': {'name': 'rahul', 'balance': 1000},
  '1068': {'name': 'roy', 'balance': 5000}},
 'Transaction': {'TR101': {'from': 1234, 'to': 9810, 'amt': 5000},
  'TR102': {'from': 9810, 'to': 1234, 'amt': 100000},
  'TR103': {'from': 1068, 'to': 9810, 'amt': 256000},
  'TR104': {'from': 9810, 'to': 1234, 'amt': 523000},
  'TR105': {'from': 1234, 'to': 1068, 'amt': 5000},
  'TR106': {'from': 9810, 'to': 1234, 'amt': 52000},
  'TR107': {'from': 1234, 'to': 9810, 'amt': 36500},
  'TR108': {'from': 1068, 'to': 1234, 'amt': 52000},
  'TR110': {'from': 1234, 'to': 9810, 'amt': 560000},
  'TR111': {'from': 9810, 'to': 1234, 'amt': 15200},
  'TR1112': {'from': 1234, 'to': 1231, 'amt': 125

In [28]:
i = 7
s = input(f"Enter a name of {i}")
print(s)